name: Publish production Typescript changes

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: yarn --dev --frozen-lockfile
      - run: yarn test
        working-directory: expo47
      # https://github.com/expo/expo-github-action
      # login to expo. using their action avoids ENOSPC: https://github.com/expo/expo-github-action/issues/20
      - uses: expo/expo-github-action@8.2.1
        with:
          expo-version: 6.x
          expo-username: erosson
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - run: npm install -g eas-cli # this one doesn't like local installs for some reason
      - run: yarn publish-ts # `expo publish` plus some prepublish chores, using eas-cli
        working-directory: expo47
